// ============================================================
// MATRA — Share Content Utility
// ============================================================

import { Share, Platform } from 'react-native';

const WATERMARK = '\n\n— Generated by AI in the Matra App 🌳';

export function shareBiography(personName: string, biography: string) {
  const message = `${personName}'s Biography\n\n${biography}${WATERMARK}`;
  return Share.share(
    Platform.OS === 'ios'
      ? { message }
      : { message, title: `${personName}'s Biography` },
  );
}

export function shareStory(title: string, content: string, toldBy?: string) {
  const attribution = toldBy ? `\nTold by ${toldBy}\n` : '\n';
  const message = `${title}${attribution}\n${content}${WATERMARK}`;
  return Share.share(
    Platform.OS === 'ios'
      ? { message }
      : { message, title },
  );
}

export function shareInterviewSummary(
  title: string,
  summary: string,
  keyTopics?: string[],
) {
  const topicsLine =
    keyTopics && keyTopics.length > 0
      ? `\n\nKey topics: ${keyTopics.join(', ')}`
      : '';
  const message = `${title}\n\n${summary}${topicsLine}${WATERMARK}`;
  return Share.share(
    Platform.OS === 'ios'
      ? { message }
      : { message, title },
  );
}
